//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DualLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the Magic Word input field.
        /// </summary>
        internal static string ActivateDescription {
            get {
                return ResourceManager.GetString("ActivateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a Magic Word for the active application.
        /// </summary>
        internal static string AddMagicWordDescription {
            get {
                return ResourceManager.GetString("AddMagicWordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs (*.exe; *.pif; *.com; *bat; *.cmd)|*.exe; *.pif; *.com; *bat; *.cmd|All files (*.*)|*.*.
        /// </summary>
        internal static string BrowseExeFilter {
            get {
                return ResourceManager.GetString("BrowseExeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowseExeTitle {
            get {
                return ResourceManager.GetString("BrowseExeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &apos;{0}&apos; MagicWord?.
        /// </summary>
        internal static string ConfirmDel1MW {
            get {
                return ResourceManager.GetString("ConfirmDel1MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all {0} selected MagicWords?.
        /// </summary>
        internal static string ConfirmDel2MW {
            get {
                return ResourceManager.GetString("ConfirmDel2MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all MagicWords?.
        /// </summary>
        internal static string ConfirmDelAllMW {
            get {
                return ResourceManager.GetString("ConfirmDelAllMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-ordinate is not valid.
        /// </summary>
        internal static string InvalidCoOrd {
            get {
                return ResourceManager.GetString("InvalidCoOrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program comes with ABSOLUTELY NO WARRANTY.
        ///This is free software, and you are welcome to redistribute it under certain conditions; please see the file named COPYING.txt for details..
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon missingIcon {
            get {
                object obj = ResourceManager.GetObject("missingIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Launcher.
        /// </summary>
        internal static string MyTitle {
            get {
                return ResourceManager.GetString("MyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to speficy the name that you will type to run this Magic Word..
        /// </summary>
        internal static string NoAlias {
            get {
                return ResourceManager.GetString("NoAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify the application/document to open for this Magic Word..
        /// </summary>
        internal static string NoFilename {
            get {
                return ResourceManager.GetString("NoFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a key from the drop down box.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlickRun data files (*.qrs)|*.qrs|All files (*.*)|*.*.
        /// </summary>
        internal static string QrsFilter {
            get {
                return ResourceManager.GetString("QrsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration of this hot key has failed.
        ///Try another hot key combination..
        /// </summary>
        internal static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximised.
        /// </summary>
        internal static string ShowMaximised {
            get {
                return ResourceManager.GetString("ShowMaximised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimised.
        /// </summary>
        internal static string ShowMinimised {
            get {
                return ResourceManager.GetString("ShowMinimised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Window.
        /// </summary>
        internal static string ShowNormal {
            get {
                return ResourceManager.GetString("ShowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TargetCursor {
            get {
                object obj = ResourceManager.GetObject("TargetCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinCrossHairs {
            get {
                object obj = ResourceManager.GetObject("WinCrossHairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinNoCrossHairs {
            get {
                object obj = ResourceManager.GetObject("WinNoCrossHairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
