//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CursorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CursorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMT.Resources.CursorStrings", typeof(CursorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to next screen.
        /// </summary>
        internal static string CursorNextScreenDescription {
            get {
                return ResourceManager.GetString("CursorNextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorNextScreenWin7 {
            get {
                return ResourceManager.GetString("CursorNextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to previous screen.
        /// </summary>
        internal static string CursorPrevScreenDescription {
            get {
                return ResourceManager.GetString("CursorPrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorPrevScreenWin7 {
            get {
                return ResourceManager.GetString("CursorPrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center cursor on primary screen.
        /// </summary>
        internal static string CursorToPrimaryScreenDescription {
            get {
                return ResourceManager.GetString("CursorToPrimaryScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorToPrimaryScreenWin7 {
            get {
                return ResourceManager.GetString("CursorToPrimaryScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor free to move between screens.
        /// </summary>
        internal static string FreeCursorDescription {
            get {
                return ResourceManager.GetString("FreeCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FreeCursorWin7 {
            get {
                return ResourceManager.GetString("FreeCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock cursor onto screen.
        /// </summary>
        internal static string LockCursorDescription {
            get {
                return ResourceManager.GetString("LockCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LockCursorWin7 {
            get {
                return ResourceManager.GetString("LockCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor movement between screens is sticky.
        /// </summary>
        internal static string StickyCursorDescription {
            get {
                return ResourceManager.GetString("StickyCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StickyCursorWin7 {
            get {
                return ResourceManager.GetString("StickyCursorWin7", resourceCulture);
            }
        }
    }
}
