//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SnapStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnapStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMT.Resources.SnapStrings", typeof(SnapStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delate all {0} snaps?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Snap to fit.
        /// </summary>
        internal static string ScaleSnap {
            get {
                return ResourceManager.GetString("ScaleSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle if to scale the snapshot to fill the second screed.
        /// </summary>
        internal static string ScaleSnapDescription {
            get {
                return ResourceManager.GetString("ScaleSnapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Snap.
        /// </summary>
        internal static string ShowSnap {
            get {
                return ResourceManager.GetString("ShowSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle display of current snapshot.
        /// </summary>
        internal static string ShowSnapDescription {
            get {
                return ResourceManager.GetString("ShowSnapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show this image..
        /// </summary>
        internal static string SnapMenuItemTooltip {
            get {
                return ResourceManager.GetString("SnapMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap!.
        /// </summary>
        internal static string SnapNow {
            get {
                return ResourceManager.GetString("SnapNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a snapshot of the primary screen.
        /// </summary>
        internal static string TakeSnapDescription {
            get {
                return ResourceManager.GetString("TakeSnapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a snapshot of the active window.
        /// </summary>
        internal static string TakeWinSnapDescription {
            get {
                return ResourceManager.GetString("TakeWinSnapDescription", resourceCulture);
            }
        }
    }
}
