//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SwapScreenStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwapScreenStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMT.Resources.SwapScreenStrings", typeof(SwapScreenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset the description and the position for all of your UDAs to suitable default values, but any hot keys that you have defined will be kept.  
        ///This is useful if your monitor count or resolutions have changed.
        ///
        ///Do you wish to continue?.
        /// </summary>
        internal static string ConfirmResetUdas {
            get {
                return ResourceManager.GetString("ConfirmResetUdas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to next screen.
        /// </summary>
        internal static string CursorNextScreenDescription {
            get {
                return ResourceManager.GetString("CursorNextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorNextScreenWin7 {
            get {
                return ResourceManager.GetString("CursorNextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to previous screen.
        /// </summary>
        internal static string CursorPrevScreenDescription {
            get {
                return ResourceManager.GetString("CursorPrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorPrevScreenWin7 {
            get {
                return ResourceManager.GetString("CursorPrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position specified is not valid.
        /// </summary>
        internal static string InvalidPosition {
            get {
                return ResourceManager.GetString("InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximise the active window.
        /// </summary>
        internal static string MaximiseDescription {
            get {
                return ResourceManager.GetString("MaximiseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Up&gt;.
        /// </summary>
        internal static string MaximiseWin7 {
            get {
                return ResourceManager.GetString("MaximiseWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise all but the active window.
        /// </summary>
        internal static string MinimiseAllButDescription {
            get {
                return ResourceManager.GetString("MinimiseAllButDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Home&gt;.
        /// </summary>
        internal static string MinimiseAllButWin7 {
            get {
                return ResourceManager.GetString("MinimiseAllButWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise the active window.
        /// </summary>
        internal static string MinimiseDescription {
            get {
                return ResourceManager.GetString("MinimiseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Down&gt;.
        /// </summary>
        internal static string MinimiseWin7 {
            get {
                return ResourceManager.GetString("MinimiseWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to next screen.
        /// </summary>
        internal static string NextScreenDescription {
            get {
                return ResourceManager.GetString("NextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+Shift+&lt;Right&gt;.
        /// </summary>
        internal static string NextScreenWin7 {
            get {
                return ResourceManager.GetString("NextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to previous screen.
        /// </summary>
        internal static string PrevScreenDescription {
            get {
                return ResourceManager.GetString("PrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+Shift+&lt;Left&gt;.
        /// </summary>
        internal static string PrevScreenWin7 {
            get {
                return ResourceManager.GetString("PrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate screens forwards.
        /// </summary>
        internal static string RotateNextDescription {
            get {
                return ResourceManager.GetString("RotateNextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RotateNextWin7 {
            get {
                return ResourceManager.GetString("RotateNextWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate screens backwards.
        /// </summary>
        internal static string RotatePrevDescription {
            get {
                return ResourceManager.GetString("RotatePrevDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RotatePrevWin7 {
            get {
                return ResourceManager.GetString("RotatePrevWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop that cursor is on.
        /// </summary>
        internal static string ShowCursorDesktopDescription {
            get {
                return ResourceManager.GetString("ShowCursorDesktopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowCursorDesktopWin7 {
            get {
                return ResourceManager.GetString("ShowCursorDesktopWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 1.
        /// </summary>
        internal static string ShowDesktop1Description {
            get {
                return ResourceManager.GetString("ShowDesktop1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop1Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop1Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 2.
        /// </summary>
        internal static string ShowDesktop2Description {
            get {
                return ResourceManager.GetString("ShowDesktop2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop2Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop2Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 3.
        /// </summary>
        internal static string ShowDesktop3Description {
            get {
                return ResourceManager.GetString("ShowDesktop3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop3Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop3Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 4.
        /// </summary>
        internal static string ShowDesktop4Description {
            get {
                return ResourceManager.GetString("ShowDesktop4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop4Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop4Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop.
        /// </summary>
        internal static string ShowDesktopDescription {
            get {
                return ResourceManager.GetString("ShowDesktopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop {0}.
        /// </summary>
        internal static string ShowDesktopNDescription {
            get {
                return ResourceManager.GetString("ShowDesktopNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktopNWin7 {
            get {
                return ResourceManager.GetString("ShowDesktopNWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window down.
        /// </summary>
        internal static string SnapDownDescription {
            get {
                return ResourceManager.GetString("SnapDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnapDownWin7 {
            get {
                return ResourceManager.GetString("SnapDownWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window left.
        /// </summary>
        internal static string SnapLeftDescription {
            get {
                return ResourceManager.GetString("SnapLeftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Left&gt;.
        /// </summary>
        internal static string SnapLeftWin7 {
            get {
                return ResourceManager.GetString("SnapLeftWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window right.
        /// </summary>
        internal static string SnapRightDescription {
            get {
                return ResourceManager.GetString("SnapRightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Right&gt;.
        /// </summary>
        internal static string SnapRightWin7 {
            get {
                return ResourceManager.GetString("SnapRightWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window up.
        /// </summary>
        internal static string SnapUpDescription {
            get {
                return ResourceManager.GetString("SnapUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnapUpWin7 {
            get {
                return ResourceManager.GetString("SnapUpWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supersize the avtive window.
        /// </summary>
        internal static string SupersizeDescription {
            get {
                return ResourceManager.GetString("SupersizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupersizeWin7 {
            get {
                return ResourceManager.GetString("SupersizeWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the active window with the next window.
        /// </summary>
        internal static string SwapTop2Description {
            get {
                return ResourceManager.GetString("SwapTop2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SwapTop2Win7 {
            get {
                return ResourceManager.GetString("SwapTop2Win7", resourceCulture);
            }
        }
    }
}
