//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapScreen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwapScreen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Swap Screen....
        /// </summary>
        internal static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to next screen.
        /// </summary>
        internal static string CursorNextScreenDescription {
            get {
                return ResourceManager.GetString("CursorNextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorNextScreenWin7 {
            get {
                return ResourceManager.GetString("CursorNextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor to previous screen.
        /// </summary>
        internal static string CursorPrevScreenDescription {
            get {
                return ResourceManager.GetString("CursorPrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CursorPrevScreenWin7 {
            get {
                return ResourceManager.GetString("CursorPrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor free to move between screens.
        /// </summary>
        internal static string FreeCursorDescription {
            get {
                return ResourceManager.GetString("FreeCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FreeCursorWin7 {
            get {
                return ResourceManager.GetString("FreeCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position specified is not valid.
        /// </summary>
        internal static string InvalidPosition {
            get {
                return ResourceManager.GetString("InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program comes with ABSOLUTELY NO WARRANTY.
        ///This is free software, and you are welcome to redistribute it under certain conditions; please see the file named COPYING.txt for details..
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock cursor onto screen.
        /// </summary>
        internal static string LockCursorDescription {
            get {
                return ResourceManager.GetString("LockCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LockCursorWin7 {
            get {
                return ResourceManager.GetString("LockCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximise the active window.
        /// </summary>
        internal static string MaximiseDescription {
            get {
                return ResourceManager.GetString("MaximiseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Up&gt;.
        /// </summary>
        internal static string MaximiseWin7 {
            get {
                return ResourceManager.GetString("MaximiseWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise all but the active window.
        /// </summary>
        internal static string MinimiseAllButDescription {
            get {
                return ResourceManager.GetString("MinimiseAllButDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Home&gt;.
        /// </summary>
        internal static string MinimiseAllButWin7 {
            get {
                return ResourceManager.GetString("MinimiseAllButWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise the active window.
        /// </summary>
        internal static string MinimiseDescription {
            get {
                return ResourceManager.GetString("MinimiseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Down&gt;.
        /// </summary>
        internal static string MinimiseWin7 {
            get {
                return ResourceManager.GetString("MinimiseWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Screen.
        /// </summary>
        internal static string MyTitle {
            get {
                return ResourceManager.GetString("MyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to next screen.
        /// </summary>
        internal static string NextScreenDescription {
            get {
                return ResourceManager.GetString("NextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+Shift+&lt;Right&gt;.
        /// </summary>
        internal static string NextScreenWin7 {
            get {
                return ResourceManager.GetString("NextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a key from the drop down box.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For future combatibility with Windows 7 you may want to use {0} for this function, as this is what Windows 7 uses..
        /// </summary>
        internal static string NotWin7 {
            get {
                return ResourceManager.GetString("NotWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active window to previous screen.
        /// </summary>
        internal static string PrevScreenDescription {
            get {
                return ResourceManager.GetString("PrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+Shift+&lt;Left&gt;.
        /// </summary>
        internal static string PrevScreenWin7 {
            get {
                return ResourceManager.GetString("PrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration of this hotkey has failed.
        ///Try another hot key combination..
        /// </summary>
        internal static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate screens forwards.
        /// </summary>
        internal static string RotateNextDescription {
            get {
                return ResourceManager.GetString("RotateNextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RotateNextWin7 {
            get {
                return ResourceManager.GetString("RotateNextWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate screens backwards.
        /// </summary>
        internal static string RotatePrevDescription {
            get {
                return ResourceManager.GetString("RotatePrevDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RotatePrevWin7 {
            get {
                return ResourceManager.GetString("RotatePrevWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 1.
        /// </summary>
        internal static string ShowDesktop1Description {
            get {
                return ResourceManager.GetString("ShowDesktop1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop1Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop1Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop 2.
        /// </summary>
        internal static string ShowDesktop2Description {
            get {
                return ResourceManager.GetString("ShowDesktop2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShowDesktop2Win7 {
            get {
                return ResourceManager.GetString("ShowDesktop2Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop {0}.
        /// </summary>
        internal static string ShowDesktopMenuItem {
            get {
                return ResourceManager.GetString("ShowDesktopMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window down.
        /// </summary>
        internal static string SnapDownDescription {
            get {
                return ResourceManager.GetString("SnapDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnapDownWin7 {
            get {
                return ResourceManager.GetString("SnapDownWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window left.
        /// </summary>
        internal static string SnapLeftDescription {
            get {
                return ResourceManager.GetString("SnapLeftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Left&gt;.
        /// </summary>
        internal static string SnapLeftWin7 {
            get {
                return ResourceManager.GetString("SnapLeftWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window right.
        /// </summary>
        internal static string SnapRightDescription {
            get {
                return ResourceManager.GetString("SnapRightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win+&lt;Right&gt;.
        /// </summary>
        internal static string SnapRightWin7 {
            get {
                return ResourceManager.GetString("SnapRightWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap active window up.
        /// </summary>
        internal static string SnapUpDescription {
            get {
                return ResourceManager.GetString("SnapUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnapUpWin7 {
            get {
                return ResourceManager.GetString("SnapUpWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor movement between screens is sticky.
        /// </summary>
        internal static string StickyCursorDescription {
            get {
                return ResourceManager.GetString("StickyCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StickyCursorWin7 {
            get {
                return ResourceManager.GetString("StickyCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supersize the avtive window.
        /// </summary>
        internal static string SupersizeDescription {
            get {
                return ResourceManager.GetString("SupersizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupersizeWin7 {
            get {
                return ResourceManager.GetString("SupersizeWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the active window with the next window.
        /// </summary>
        internal static string SwapTop2Description {
            get {
                return ResourceManager.GetString("SwapTop2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SwapTop2Win7 {
            get {
                return ResourceManager.GetString("SwapTop2Win7", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TargetCursor {
            get {
                object obj = ResourceManager.GetObject("TargetCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is already provided by Windows 7 using {0}, so there is no need to enable this unless you want SwapScreen to handle it using a different hotkey..
        /// </summary>
        internal static string Win7 {
            get {
                return ResourceManager.GetString("Win7", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WinCrossHairs {
            get {
                object obj = ResourceManager.GetObject("WinCrossHairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinNoCrossHairs {
            get {
                object obj = ResourceManager.GetObject("WinNoCrossHairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
